# name: 'user-srv'
# mysql:
#   host: '172.18.81.229'
#   port: 3306
#   user: 'root'
#   password: 'root'
#   name: 'mxshop_user_srv'

# consul:
#   host: '172.18.81.229' # consul 地址
#   port: 8500

# nacos: # 其他配置全部从nacos中获取
host: "172.18.81.229"
port: 8848
namespace: "ef4b6ceb-98a6-4f17-a02a-17c6d49a4da8"
user: "nacos"
password: "nacos"
dataid: "goods-srv.json"
group: "dev"
